apiVersion: spyderbat/v1
kind: SpyderbatPolicy
metadata:
  name: apt-news.service-policy
  type: linux-service
  latestTimestamp: 1678081602.5822384
spec:
  serviceSelector:
    cgroup: systemd:/system.slice/apt-news.service
  processPolicy:
  - name: python3
    exe:
    - /usr/bin/python3.8
    id: python3_0
    euser:
    - root
    children:
    - name: uname
      exe:
      - /usr/bin/uname
      id: uname_0
  networkPolicy:
    ingress: []
    egress: []
  response:
    default:
    - makeRedFlag:
        severity: info
        content: 'This is a provisional flag indicating a would-be policy violation. Use the `spyctl merge` command to tailor this policy to your environment, and update the severity as needed.'                     
    actions: []

