apiVersion: spyderbat/v1
kind: SpyderbatPolicy
metadata:
  name: chronyd.service-policy
  type: linux-service
  latestTimestamp: 1677780073.8570778
spec:
  serviceSelector:
    cgroup: systemd:/system.slice/chronyd.service
  processPolicy:
  - name: chronyd
    exe:
    - /usr/sbin/chronyd
    id: chronyd_0
    euser:
    - chrony
    - root
    children:
    - name: chronyd
      exe:
      - /usr/sbin/chronyd
      id: chronyd_1
      euser:
      - chrony
  networkPolicy:
    ingress: []
    egress:  []
  response:
    default:
    - makeRedFlag:
        severity: info
        content: 'This is a provisional flag indicating a would-be policy violation. Use the `spyctl merge` command to tailor this policy to your environment, and update the severity as needed.'      
    actions: []
