apiVersion: spyderbat/v1
kind: SpyderbatPolicy
metadata:
  name: containerd.service-policy
  type: linux-service
  latestTimestamp: 1677837658.8593864
spec:
  serviceSelector:
    cgroup: systemd:/system.slice/containerd.service
  processPolicy:
  - name: containerd
    exe:
    - /usr/bin/containerd
    id: containerd_0
    euser:
    - root
    listeningSockets:        
    - protocol: TCP
      port: 32867
    - protocol: TCP
      port: 33567
    - protocol: TCP
      port: 33771
    - protocol: TCP
      port: 34205
    - protocol: TCP
      port: 35095
    - protocol: TCP
      port: 35753
    - protocol: TCP
      port: 37563
    - protocol: TCP
      port: 38235
    - protocol: TCP
      port: 39205
    - protocol: TCP
      port: 39953
    - protocol: TCP
      port: 41377
    - protocol: TCP
      port: 42337
    - protocol: TCP
      port: 42771
    - protocol: TCP
      port: 43437
    - protocol: TCP
      port: 44053
    - protocol: TCP
      port: 46063
    - protocol: TCP
      port: 46179
    children:
    - name: containerd-shim
      exe:
      - /usr/bin/containerd-shim-runc-v2
      id: containerd-shim_0
      children:
      - name: containerd-shim
        exe:
        - /usr/bin/containerd-shim-runc-v2
        id: containerd-shim_1
        children:
        - name: runc
          exe:
          - /usr/sbin/runc
          id: runc_0
          children:
          - name: *
            exe:
            - /
            id: '6_0'
          - name: exe
            exe:
            - /usr/bin/dockerd
            id: exe_0
          - name: exe
            exe:
            - /usr/sbin/runc
            id: exe_2
          - name: runc:[0:PARENT]
            exe:
            - /
            id: runc:[0:parent]_1
      - name: runc
        exe:
        - /usr/sbin/runc
        id: runc_1
        children:
        - name: '6'
          exe:
          - /
          id: '6_1'
        - name: exe
          exe:
          - /usr/bin/dockerd
          id: exe_1
        - name: exe
          exe:
          - /usr/sbin/runc
          id: exe_3
  - name: containerd-shim
    exe:
    - /usr/bin/containerd-shim-runc-v2
    id: containerd-shim_2
    euser:
    - root
    children:
    - name: '5'
      exe:
      - /
      id: '5_1'
    - name: runc
      exe:
      - /usr/sbin/runc
      id: runc_2
      children:
      - name: '5'
        exe:
        - /
        id: '5_0'
      - name: runc:[0:PARENT]
        exe:
        - /
        id: runc:[0:parent]_0
  - name: '6'
    exe:
    - /
    id: '6_2'
    euser:
    - root
  networkPolicy:
    ingress: []
    egress: []
  response:
    default:
    - makeRedFlag:
        severity: info
        content: 'This is a provisional flag indicating a would-be policy violation. Use the `spyctl merge` command to tailor this policy to your environment, and update the severity as needed.'           
    actions: []
