apiVersion: spyderbat/v1
kind: SpyderbatPolicy
metadata:
  name: man-db.service-policy
  type: linux-service
  latestTimestamp: 1678061022.5644116
spec:
  serviceSelector:
    cgroup: systemd:/system.slice/man-db.service
  processPolicy:
  - name: find
    exe:
    - /usr/bin/find
    id: find_0
    euser:
    - man
  - name: mandb
    exe:
    - /usr/bin/mandb
    id: mandb_0
    euser:
    - man
  networkPolicy:
    ingress: []
    egress: []
  response:
    default:
    - makeRedFlag:
        severity: info
        content: 'This is a provisional flag indicating a would-be policy violation. Use the `spyctl merge` command to tailor this policy to your environment, and update the severity as needed.'                     
    actions: []

