apiVersion: spyderbat/v1
kind: SpyderbatPolicy
metadata:
  name: nano_agent.service-policy
  type: linux-service
  latestTimestamp: 1677862871.9575238
spec:
  serviceSelector:
    cgroup: systemd:/system.slice/nano_agent.service
  processPolicy:
  - name: Nano Agent
    exe:
    - /opt/spyderbat/bin/nano_agent-v1.1.40
    id: nano_agent_0
    euser:
    - root
    children:
    - name: Auth
      exe:
      - /opt/spyderbat/tmp/bat*
      id: auth_0
    - name: Bashbat
      exe:
      - /opt/spyderbat/tmp/bat*
      id: bashbat_0
    - name: Grimreaper
      exe:
      - /opt/spyderbat/tmp/bat*
      id: grimreaper_0
    - name: Procmon
      exe:
      - /opt/spyderbat/tmp/bat*
      id: procmon_0
      children:
      - name: lsof
        exe:
        - /usr/bin/lsof
        - /usr/sbin/lsof
        id: lsof_0
    - name: Scentless
      exe:
      - /opt/spyderbat/tmp/bat*
      id: scentless_0
    - name: Snapshot
      exe:
      - /opt/spyderbat/tmp/bat*
      id: snapshot_0
      children:
      - name: dpkg-query
        exe:
        - /usr/bin/dpkg-query
        id: dpkg-query_0
      - name: ip
        exe:
        - /usr/bin/ip
        - /usr/sbin/ip
        id: ip_0
      - name: loginctl
        exe:
        - /usr/bin/loginctl
        id: loginctl_0
      - name: lsof
        exe:
        - /usr/bin/lsof
        - /usr/sbin/lsof
        id: lsof_1
      - name: rpm
        exe:
        - /usr/bin/rpm
        id: rpm_0
      - name: uname
        exe:
        - /usr/bin/uname
        id: uname_0
    - name: bat*
      exe:
      - /opt/spyderbat/tmp/bat*
      id: bat_0
      children:
      - name: ip
        exe:
        - /usr/sbin/ip
        id: ip_1
      - name: loginctl
        exe:
        - /usr/bin/loginctl
        id: loginctl_1
      - name: lsof
        exe:
        - /usr/sbin/lsof
        id: lsof_2
      - name: rpm
        exe:
        - /usr/bin/rpm
        id: rpm_1
      - name: uname
        exe:
        - /usr/bin/uname
        id: uname_1
  - name: lsof
    exe:
    - /usr/sbin/lsof
    id: lsof_3
    euser:
    - root
  networkPolicy:
    ingress: []
    egress:
    - to:
      - ipBlock:
          cidr: 169.254.169.254/32
      processes:
      - nano_agent_0
      - snapshot_0
      ports:
      - protocol: TCP
        port: 80
    - to:
      - dnsSelector:
        - orc.kangaroobat.net
      processes:
      - nano_agent_0
      ports:
      - protocol: TCP
        port: 443
    - to:
      - dnsSelector:
        - ec2.amazonaws.com
      - dnsSelector:
        - ec2.eu-central-1.amazonaws.com
      - ipBlock:
          cidr: 52.46.140.46/32
      - ipBlock:
          cidr: 52.46.142.40/32
      - ipBlock:
          cidr: 52.46.142.78/32
      - ipBlock:
          cidr: 52.46.142.79/32
      - ipBlock:
          cidr: 52.46.143.246/32
      - ipBlock:
          cidr: 52.46.146.93/32
      - ipBlock:
          cidr: 52.46.146.198/32
      - ipBlock:
          cidr: 52.46.147.69/32
      - ipBlock:
          cidr: 52.46.150.54/32
      - ipBlock:
          cidr: 52.46.150.99/32
      - ipBlock:
          cidr: 52.46.155.190/32
      - ipBlock:
          cidr: 52.46.159.174/32
      - ipBlock:
          cidr: 52.94.136.219/32
      - ipBlock:
          cidr: 52.94.232.172/32
      - ipBlock:
          cidr: 52.94.233.135/32
      - ipBlock:
          cidr: 54.239.23.99/32
      - ipBlock:
          cidr: 54.239.28.168/32
      - ipBlock:
          cidr: 54.239.29.8/32
      - ipBlock:
          cidr: 54.239.31.174/32
      - ipBlock:
          cidr: 54.239.55.155/32
      - ipBlock:
          cidr: 54.239.55.167/32
      - ipBlock:
          cidr: 209.54.177.244/32
      - ipBlock:
          cidr: 209.54.177.247/32
      - ipBlock:
          cidr: 209.54.180.155/32
      - ipBlock:
          cidr: 209.54.180.217/32
      - ipBlock:
          cidr: 209.54.181.135/32
      - ipBlock:
          cidr: 209.54.181.169/32
      - ipBlock:
          cidr: 209.54.181.192/32
      - ipBlock:
          cidr: 209.54.181.193/32
      - ipBlock:
          cidr: 209.54.181.194/32
      - ipBlock:
          cidr: 209.54.181.208/32
      - ipBlock:
          cidr: 209.54.181.211/32
      - ipBlock:
          cidr: 209.54.181.212/32
      - ipBlock:
          cidr: 209.54.182.34/32
      - ipBlock:
          cidr: 209.54.182.49/32
      - ipBlock:
          cidr: 209.54.182.67/32
      - ipBlock:
          cidr: 209.54.182.73/32
      - ipBlock:
          cidr: 209.54.182.94/32
      - ipBlock:
          cidr: 209.54.182.97/32
      processes:
      - nano_agent_0
      - snapshot_0
      ports:
      - protocol: TCP
        port: 443
    - to:
      - ipBlock:
          cidr: 169.254.169.254/32
      processes:
      - bat_0
      - nano_agent_0
      - snapshot_0
      ports:
      - protocol: TCP
        port: 80
    - to:
      - dnsSelector:
        - ec2.amazonaws.com
      - dnsSelector:
        - ec2.eu-central-1.amazonaws.com
      - ipBlock:
          cidr: 52.94.136.219/32
      - ipBlock:
          cidr: 52.94.233.135/32
      - ipBlock:
          cidr: 54.239.23.99/32
      - ipBlock:
          cidr: 54.239.55.155/32
      - ipBlock:
          cidr: 54.239.55.167/32
      - ipBlock:
          cidr: 209.54.181.212/32
      processes:
      - bat_0
      - nano_agent_0
      - snapshot_0
      ports:
      - protocol: TCP
        port: 443
    - to:
      - ipBlock:
          cidr: 10.0.0.2/32
      processes:
      - nano_agent_0
      ports:
      - protocol: TCP
        port: 53
  response:
    default:
    - makeRedFlag:
        severity: info
        content: This is a provisional flag indicating a would-be policy violation.
          Use the `spyctl merge` command to tailor this policy to your environment,
          and update the severity as needed.
    actions: []

