apiVersion: spyderbat/v1
kind: SpyderbatPolicy
metadata:
  name: packagekit.service-policy
  type: linux-service
  latestTimestamp: 1678081872.7946372
spec:
  serviceSelector:
    cgroup: systemd:/system.slice/packagekit.service
  processPolicy:
  - name: packagekitd
    exe:
    - /usr/lib/packagekit/packagekitd
    id: packagekitd_0
    euser:
    - root
    children:
    - name: dpkg
      exe:
      - /usr/bin/dpkg
      id: dpkg_0
  networkPolicy:
    ingress: []
    egress: []
  response:
    default:
    - makeRedFlag:
        severity: info
        content: 'This is a provisional flag indicating a would-be policy violation. Use the `spyctl merge` command to tailor this policy to your environment, and update the severity as needed.'
    actions: []

