apiVersion: spyderbat/v1
kind: SpyderbatPolicy
metadata:
  name: queue_eater.service-policy
  type: linux-service
  latestTimestamp: 1678089610.629574
spec:
  serviceSelector:
    cgroup: systemd:/system.slice/queue_eater.service
  processPolicy:
  - name: startq.sh
    exe:
    - /usr/bin/bash
    id: startq.sh_0
    euser:
    - ubuntu
    children:
    - name: python3
      exe:
      - /usr/bin/python3.8
      id: python3_0
  networkPolicy:
    ingress: []
    egress: []
  response:
    default:
    - makeRedFlag:
        severity: info
        content: 'This is a provisional flag indicating a would-be policy violation. Use the `spyctl merge` command to tailor this policy to your environment, and update the severity as needed.'
    actions: []

