apiVersion: spyderbat/v1
kind: SpyderbatPolicy
metadata:
  name: redis-server.service-policy
  type: linux-service
  latestTimestamp: 1678089658.4500272
spec:
  serviceSelector:
    cgroup: systemd:/system.slice/redis-server.service
  processPolicy:
  - name: redis-server
    exe:
    - /usr/bin/redis-check-rdb
    id: redis-server_0
    euser:
    - redis
    listeningSockets:
    - port: 6379
      protocol: TCP
  networkPolicy:
    ingress: []
    egress: []
  response:
    default:
    - makeRedFlag:
        severity: info
        content: 'This is a provisional flag indicating a would-be policy violation. Use the `spyctl merge` command to tailor this policy to your environment, and update the severity as needed.'
    actions: []

