apiVersion: spyderbat/v1
kind: SpyderbatPolicy
metadata:
  name: rsyslog.service-policy
  type: linux-service
  latestTimestamp: 1678089671.5142767
spec:
  serviceSelector:
    cgroup: systemd:/system.slice/rsyslog.service
  processPolicy:
  - name: rsyslogd
    exe:
    - /usr/sbin/rsyslogd
    id: rsyslogd_0
    euser:
    - root
    - syslog
  networkPolicy:
    ingress: []
    egress: []
  response:
    default:
    - makeRedFlag:
        severity: info
        content: 'This is a provisional flag indicating a would-be policy violation. Use the `spyctl merge` command to tailor this policy to your environment, and update the severity as needed.'
    actions: []

