apiVersion: spyderbat/v1
kind: SpyderbatPolicy
metadata:
  name: systemd-timesyncd.service-policy
  type: linux-service
  latestTimestamp: 1678093209.9782887
spec:
  serviceSelector:
    cgroup: systemd:/system.slice/systemd-timesyncd.service
  processPolicy:
  - name: systemd-timesyn
    exe:
    - /usr/lib/systemd/systemd-timesyncd
    id: systemd-timesyn_0
    euser:
    - systemd-timesync
  networkPolicy:
    ingress: []
    egress: []
  response:
    default:
    - makeRedFlag:
        severity: info
        content: 'This is a provisional flag indicating a would-be policy violation. Use the `spyctl merge` command to tailor this policy to your environment, and update the severity as needed.'
    actions: []

