apiVersion: spyderbat/v1
kind: SpyderbatPolicy
metadata:
  name: systemd-resolved.service-policy
  type: linux-service
  latestTimestamp: 1678093257.6019437
spec:
  serviceSelector:
    cgroup: systemd:/system.slice/systemd-resolved.service
  processPolicy:
  - name: systemd-resolve
    exe:
    - /usr/lib/systemd/systemd-resolved
    id: systemd-resolve_0
    euser:
    - systemd-resolve
    listeningSockets:
    - protocol: TCP
      port: 53
  networkPolicy:
    ingress: []
    egress: []
  response:
    default:
    - makeRedFlag:
        severity: info
        content: 'This is a provisional flag indicating a would-be policy violation. Use the `spyctl merge` command to tailor this policy to your environment, and update the severity as needed.'
    actions: []

